### ISSUE TITLE
Drop support for versions below Node.js 6

### ISSUE THREAD

**Issue by Siilwyn** [moxystudio/node-cross-spawn#108]
Something for the future, I was looking into reducing my CLI tool size and noticed the `semver` package at the top when sorting by size.

When going with Node.js 6 and higher two dependencies, `semver` and `nice-try` are not needed anymore since they are used only once for feature detection here:
https://github.com/moxystudio/node-cross-spawn/blob/bbd342bd7d94ffdf8a9418190c3fb947b72aca73/lib/parse.js#L15

**Comment by satazor** [comment]
Node 6 is reaching EOL in April. In May, I will remove both node 4 and 6 support in a single release.

**Comment by ehmicky** [comment]
@satazor, any news on this? Thanks!

**Comment by satazor** [comment]
It’s time to remove support for older Node versions. @Siilwyn @ehmicky want to give this a try?

**Comment by Siilwyn** [comment]
@satazor https://github.com/moxystudio/node-cross-spawn/pull/125

**Comment by satazor** [comment]
#125 was merged!

**Comment by satazor** [comment]
I will release a new version in the next hours.
