### ISSUE TITLE
Improper documentation

### ISSUE THREAD

**Issue by jimitpatel** [moxystudio/node-cross-spawn#119]
Documentation do not provide sufficient information on what is the parameter used under spawn command. The document is only for those who are into javascript for few years. Not recommended for new buddies or new learners

**Comment by satazor** [comment]
Hello!

In the usage section, we have this: 

> Exactly the same way as node's spawn or spawnSync, so it's a drop in replacement.

Where `spawn` and `spawnSync` link to nodejs documentation where all the arguments are described I detail.

Even for newcomers, it’s pretty explicit. What suggestion do you have to be more welcoming?

**Comment by satazor** [comment]
Closing this for now.
