### ISSUE TITLE
How to store the value of a command?

### ISSUE THREAD

**Issue by amiteshore** [moxystudio/node-cross-spawn#120]
Hello, 

Actually I'm building a CLI app, I want to ask users some question, like project name or project author. And I want to give them default value of project author as git user.name. 

My code below:

```js
const spawn = require('cross-spawn')
const { red } = require('chalk')

const { error } = console

const child = spawn('git', ['config', 'user.name'], { stdio: 'inherit' })

child.on('close', code => {
  if (code !== 0) {
    error(red(`Process exited with error code ${code}`))
  }
})
```

This code is perfectly printing the git user.name in the console but I want to store it in a variable or something like that so I can use it in the future. 

Note: My app is a lot like `npm init` or `yarn init` command. It just asks some questions with some default values  and creates a config file.

Thank you 🙏

**Comment by sindresorhus** [comment]
If you mean "persistently store the value", you probably want [`conf`](https://github.com/sindresorhus/conf).

**Comment by amiteshore** [comment]
Thank you @sindresorhus.
It's working.
