### ISSUE TITLE
Does not work inside workers threads

### ISSUE THREAD

**Issue by luizfelipe94** [moxystudio/node-cross-spawn#124]
I am trying to use execa by running code in worker threads, and it is generating the TypeError error [ERR_WORKER_UNSUPPORTED_OPERATION]: process.chdir () is not supported in workers.

process.chdir(cwd)

**Comment by ehmicky** [comment]
Related execa issue: #357

**Comment by satazor** [comment]
Seems easily solvable by adding a try catch just like the one we are doing above. Care to do a PR?

**Comment by ehmicky** [comment]
I can do that, but I don't know if I would have time to add a unit test since I'm not familiar with the test setup yet. Would it be ok to send PR without a unit test for this?

**Comment by satazor** [comment]
Yep!

**Comment by ehmicky** [comment]
Done at #127.
