### ISSUE TITLE
Does not work inside workers threads with custom current working directory

### ISSUE THREAD

**Issue by Lakitna** [moxystudio/node-cross-spawn#130]
I'm using `node-cross-spawn` via `execa` inside a worker thread. 

I seem to have found an issue related to #127 that only pops up if you set a custom cwd.

I've traced the error back to this line: <https://github.com/moxystudio/node-cross-spawn/blob/master/lib/util/resolveCommand.js#L11>

When we're running in a worker thread `process.chdir` is not `undefined`. Instead, it's a named function.

```javascript
console.log(process.chdir);
// [Function: unavailableInWorker] { disabled: true }
```

Therefore `shouldSwitchCwd` is `true` when running in a worker thread with custom cwd.

I can see one reliable way of improving this check:

```javascript
const { isMainThread } = require('worker_threads');

const shouldSwitchCwd = hasCustomCwd && isMainThread;
```

Though I'm not sure what would happen to the cwd option and how it would affect things. I'm not very well versed in these matters. These changes do fix the issue for me in any case so I'll make a PR for this change.

**Comment by satazor** [comment]
Thanks @Lakitna for the PR.

Can you check this out @ehmicky?

**Comment by ehmicky** [comment]
Fixed in #132.

**Comment by satazor** [comment]
@Lakitna it seems that @ehmicky is more correct, can you check it it solved the issue you are having before merging?

**Comment by Lakitna** [comment]
Yeah, that looks much nicer.

It works just fine on node@13 :)
