### ISSUE TITLE
Cannot download v7.0.3

### ISSUE THREAD

**Issue by elinskytap** [moxystudio/node-cross-spawn#134]
I have an issue when yarning the package. The error message is as below
```
error An unexpected error occurred: "xxx/cross-spawn/-/cross-spawn-7.0.3.tgz: Request failed \"500 Internal Server Error\"".
```
Does anyone have the same issue?

**Comment by guilhermedeandrade** [comment]
Which command did you run? Was it `yarn add cross-spawn@7.0.3`? If so, I couldn't reproduce it here

**Comment by elinskytap** [comment]
I think that is an internal issue with verdaccio. Thanks for taking a look!

**Comment by guilhermedeandrade** [comment]
> I think that is an internal issue with verdaccio. Thanks for taking a look!

You're welcome!
