### ISSUE TITLE
7.0.4 release breaks windows

### ISSUE THREAD

**Issue by achingbrain** [moxystudio/node-cross-spawn#163]
The change in this commit: https://github.com/moxystudio/node-cross-spawn/commit/5ff3a07d9add449021d806e45c4168203aa833ff#diff-7b6c860fc27e47e0176b07d4bbb28c750651fe1fcf59bd207e9eaa7c47dab0ddL26 breaks windows.

I'm trying to [run](https://github.com/ipfs/aegir/blob/master/src/run.js#L33) `npm run test` via execa (which uses this module) and it now fails with:

```
Unknown command: "run$1$1"
```

E.g.: https://github.com/libp2p/js-libp2p/actions/runs/11722923623/job/32653668053

Undoing the change from the commit above makes everything start working again.

Refs: https://github.com/sindresorhus/execa/issues/578

**Comment by satazor** [comment]
#162 should fix this, just waiting for the tests to run

**Comment by satazor** [comment]
cross-spawn@7.0.5

**Comment by achingbrain** [comment]
The fix works, thanks for the speedy resolution.
