### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by 0xTheProDev** [moxystudio/node-cross-spawn#168]
[This line](https://github.com/moxystudio/node-cross-spawn/blob/77cd97f3ca7b62c904a63a698fc4a79bf41977d0/lib/util/resolveCommand.js#L5) requires an ESM package with `require` syntax that breaks for Node v22+ systems.

**Comment by satazor** [comment]
This project has a dependency on path-key v3, which is an CJS module: https://github.com/sindresorhus/path-key/tree/v3.1.1

Are you overriding path-key anywhere in package.json?

**Comment by satazor** [comment]
Closing this for now
