### ISSUE TITLE
Paths with NTFS JUNCTIONS (links)

### ISSUE THREAD

**Issue by SteveALee** [moxystudio/node-cross-spawn#78]
If I pass a file such as `node_modules\foo\index.js` as the 2nd arg to spawn.sync,  where foo is  a JUNCTION (NTFS link) to another folder then I get the error

"The system cannot find the file specified!"

It's obviously not following through the link

This situation occurs when locally developing a package andwanting to run somehting in it.

**Comment by satazor** [comment]
@SteveALee Sorry for the late response. Could you please add a failing test case so I can fix the issue?

**Comment by satazor** [comment]
Cool! I will be releasing a major version soon that will:
- solve a bug that I've found when an argument is something like `"foo | bar"`
- fix #77 

I was hoping to address this too, but I think we can release a minor afterwards.

**Comment by satazor** [comment]
@SteveALee I've landed the changes into master. Are you willing to look into this?

**Comment by SteveALee** [comment]
Sure, but will be at end of the week. Thanks!!!

**Comment by SteveALee** [comment]
@satazor I'm unable to reproduce now. Thanks

**Comment by satazor** [comment]
Wow nice! Will close this then.
