### ISSUE TITLE
Child process hangs

### ISSUE THREAD

**Issue by annakocheshkova** [moxystudio/node-cross-spawn#96]
I'm using the library to execute a command in terminal:

```
process = spawn(command, params, options);
process.stdout.on('data', onLine);
process.stderr.on('data', onLine);
process.on('error', onError);
process.on('close', onClose);
```
It enters `onLine` several times with the output, but then just hangs and does nothing (no exit, no error). What are the possible reasons for that? Is that a bug?

If I execute the command in Terminal, everything's fine. The command is linking a module to react native application (react-native link).

**Comment by satazor** [comment]
It's hard to tell if that's a bug from your side or our side. I suggest that you use Node's `spawn` and see if the bug still manifests. If it does, then it's a bug on your side, otherwise it's on our side.

Makes sense?

**Comment by annakocheshkova** [comment]
@satazor actually one of the reasons I switched to your lib is that node's spawn was giving me `spawn raect-native ENOENT`

**Comment by annakocheshkova** [comment]
@satazor Oh you mean use local react-native.cmd with Node spawn? No, it still gives me ` spawn "/node_modules/.bin/react-native.cmd" ENOENT`

**Comment by satazor** [comment]
The path should be relative, it seems you are using it absolutely because of the trailing `/`

**Comment by satazor** [comment]
Anyway, it would be more helpful if you could give me a reproducible test case so that I can help you in a easier way.

**Comment by annakocheshkova** [comment]
How is it then? Same for `./node_modules/.bin/react-native.cmd` and `node_modules/.bin/react-native.cmd`

I'm using it to run a `react-native link` inside of the RN app:
`react-native init sample-app`
`cd sample-app`
`react-native i appcenter appcenter-analytics`

Then in my node js app, inside of the sample app folder, I use the following code to execute `react-native link` automatically:

```
process = spawn("react-native", ["link", "appcenter"], {cwd: <absolute path to app here>});
process.stdout.on('data', onLine);
process.stderr.on('data', onLine);
process.on('error', onError);
process.on('close', onClose);
```

Then I check whether it hits any of the callbacks, I get some of the output lines in `onLine` callback, then it disappears.

**Comment by satazor** [comment]
Alright, I will try to replicate. Give me a few minutes.

**Comment by annakocheshkova** [comment]
@satazor Have found a hint... The process gives no output because it waits for the input. But it doesn't send the actual line that is before the output (where is it lost?). So, in short, it waits for the input a line earlier than it is in reality.

In example, the command output is:
```
Configuring Analytics...
What is the Android app secret?
<waits for the input>
```

What I actually get in stdout callback is just `Configuring Analytics...` and that' all.

**Comment by satazor** [comment]
I see.

Have you tried setting stdio to `inherit`? https://nodejs.org/api/child_process.html#child_process_options_stdio

**Comment by annakocheshkova** [comment]
@satazor No it didn't help. Actually I have found out that the issue is deeper and actually is in `node`, not your lib, and the process hangs even with `eexec` and even if the input is provided..
So anyway, huge thanks for help, I think im gonna open an issue in their repo.
